import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer.js'

// let black = #000000
// let grey = #242424
// let white = #FBFAEE
// let lightpurple  = #933DC9
// let purple = #53118F
 
export default function Home() {
  return (
    <div className={styles.parentcontainer}>
      <Head>
        <title>WISDOM ACADEMY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Screenshot2 (108).png" />
      </Head>

      <main className={styles.main}>
        <div className={styles.landing}>

  
        <div className={styles.container}>
          <h1 className={styles.head1}>WISDOM ACADEMY</h1>
          <h3>Youth leading online Education app  </h3>
          <p>Wisdom Academy is a education provider based across the India in secondary and higher education. We promise to lift you to your highest dreams.
            Let us change your view about education. Our top faculities will make it happen through your handheld device.</p>
          <div className={styles.btnContainer}>
          <button className={styles.btn}>Get Started</button>
          <button className={styles.btn2}>Explore</button>

          </div>
          
        </div>
        <div className={styles.companion}>
          <Image className={styles.image}src="/undraw_online_video_re_fou2.svg" width={500} height={500} ></Image>
        </div>
        </div>

        <div className={styles.box} style={{zIndex:1}}>
          <div className={styles.childBox1}>
         
           <Image src="/undraw_online_video_re_fou2.svg" width={150} height={150}></Image>
           <h1>Learn</h1> 
            </div>
          <div className={styles.childBox2}>
            <Image src="/undraw_online_learning_re_qw08.svg" width={150} height={150}></Image>
            <h1>Practice</h1>
            </div>
          <div className={styles.childBox3}>
             <Image src="/undraw_segment_analysis_re_ocsl.svg" width={150} height={150}></Image>
             <h1>Analyse</h1>
             </div>
        </div>

        <div className={styles.info}>
          <div className={styles.infoImage}>
            <Image src="/undraw_group_video_re_btu7.svg" width={500} height={500}></Image>
          </div>
          <div className={styles.infoDes}>
            <h1 className={styles.infoH1}>Join our special 2:8 classes</h1>
            <p className={styles.infoP}>where our best eduacators explain concepts and live teachers clear your doubts. Also less ratio for students will make class more attentive. </p>
          </div>

        </div>

        <div className={styles.enroll}>
          <h1>Enroll now!</h1>
          <button className={styles.button}>Enroll</button>
        </div>
      </main>

     
      <Footer/>
    </div>
  )
}
